### PR TITLE
Add support for NIP-55

### PR DESCRIPTION
**Pull request by chebizarro**
This pull request adds support for NIP-55 as per coracle-social/coracle#421

> * [X]  Add Nip55Signer to @welshman/signer with dependency injection for sending/receiving intents based on an interface
> * [X]  Add support to @welshman/app's `getSigner` function

This should probably result in a version number bump as well, once the PR is accepted

### CODE REVIEW

**Comment by chebizarro** [comment]
The prepare script for the plugin wasn't running properly on npm install and the package-lock.json was retaining an old commit hash. The latest push builds for me from a fresh pull of the issue#421 branch.

Adding the plugin as a peer dependency avoids having to convert the signer package to a capacitor plugin since it doesn't call any native code directly.

There's a bug that is preventing Coracle from fully loading with this version, but I suspect it's in the session code for Coracle itself, so I'm going to dig a bit deeper into that.

**Comment by staab** [comment]
Got it, that all makes sense. Peer dependency it is.

> There's a bug that is preventing Coracle from fully loading with this version, but I suspect it's in the session code for Coracle itself, so I'm going to dig a bit deeper into that.

Looks like you just forgot to pass the package name in when calling `addSession`. This fixes it:

```
export const loginWithAmber = pubkey =>
  addSession({method: "nip55", pubkey, package: 'com.greenart7c3.nostrsigner'})
```

That brings up another question though — is it possible to avoid hard-coding the specific package? Maybe by querying for ` `nostrsigner:` handlers?

**Comment by chebizarro** [comment]
> That brings up another question though — is it possible to avoid hard-coding the specific package? Maybe by querying for `nostrsigner:` handlers?

Yes it is! The same query to the Package Manager returns enough info to create a list of the Packages, their name and their icon. I'm pushing an update to the plugin shortly that will include this feature as well as support for the Content Resolver to reduce the amount of round trips using Intents which will improve the UX greatly.

**Comment by staab** [comment]
This has been merged: https://github.com/coracle-social/welshman/commit/e1f8d6a4e03c6aeaa697c9d9e2d9975da9b1c238

**Pull request closed without merging**
